using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataModel {

	public class hewemp {
		public int sqlid { get; set; }
		public int foxid { get; set; }
		public string queop { get; set; }
		public string name { get; set; }
		public string badge { get; set; }
		public string emp_no { get; set; }
		public string address { get; set; }
		public string city { get; set; }
		public string state { get; set; }
		public string zip { get; set; }
		public string phone { get; set; }
		public string dept { get; set; }
		public DateTime? raise { get; set; }
		public decimal pay_rate { get; set; }
		public decimal pay_rate2 { get; set; }
		public int shift { get; set; }
		public string comment { get; set; }
		public string lname { get; set; }
		public DateTime? birth { get; set; }
		public decimal totalhrs { get; set; }
		public DateTime? hiredate { get; set; }
		public string jobclass { get; set; }
		public string empclass { get; set; }
		public decimal base_rate { get; set; }
		public string union { get; set; }
		public DateTime? biddate { get; set; }
		public DateTime? progdate { get; set; }
		public string ssnumber { get; set; }
		public string reg { get; set; }
		public DateTime? reg_date { get; set; }
		public bool inactive { get; set; }
		public string marital { get; set; }
		public string taxmarital { get; set; }
		public string taxstate { get; set; }
		public string st_marital { get; set; }
		public int st_deduct { get; set; }
		public string sec125 { get; set; }
		public int deductions { get; set; }
		public decimal pgarnish { get; set; }
		public decimal d1 { get; set; }
		public decimal d2 { get; set; }
		public decimal d3 { get; set; }
		public decimal d4 { get; set; }
		public decimal d5 { get; set; }
		public decimal d6 { get; set; }
		public decimal d7 { get; set; }
		public decimal d8 { get; set; }
		public decimal d1y { get; set; }
		public decimal d2y { get; set; }
		public decimal d3y { get; set; }
		public decimal d4y { get; set; }
		public decimal d5y { get; set; }
		public decimal d6y { get; set; }
		public decimal d7y { get; set; }
		public decimal d8y { get; set; }
		public DateTime? quit_date { get; set; }
		public string quit_code { get; set; }
		public decimal hrs { get; set; }
		public decimal othrs { get; set; }
		public decimal dothrs { get; set; }
		public decimal holhrs { get; set; }
		public decimal vachrs { get; set; }
		public decimal funhrs { get; set; }
		public decimal regpay { get; set; }
		public decimal otpay { get; set; }
		public decimal dotpay { get; set; }
		public decimal holpay { get; set; }
		public decimal vacpay { get; set; }
		public decimal otherpay { get; set; }
		public decimal gross { get; set; }
		public decimal net { get; set; }
		public decimal qtr1 { get; set; }
		public decimal qtr2 { get; set; }
		public decimal qtr3 { get; set; }
		public decimal qtr4 { get; set; }
		public decimal med { get; set; }
		public decimal fica { get; set; }
		public decimal fedwh { get; set; }
		public decimal statewh { get; set; }
		public decimal faddwith { get; set; }
		public decimal saddwith { get; set; }
		public decimal garnish { get; set; }
		public string trucker { get; set; }
		public int workorder { get; set; }
		public string operation { get; set; }
		public int workorderf { get; set; }
		public string operationf { get; set; }
		public string start { get; set; }
		public DateTime? startdate { get; set; }
		public int no_emps { get; set; }
		public int tmade { get; set; }
		public int tscrap { get; set; }
		public int paydays { get; set; }
		public DateTime? warn_date { get; set; }
		public decimal warn_avg { get; set; }
		public DateTime? warn_expir { get; set; }
		public DateTime? verb_date { get; set; }
		public decimal verb_avg { get; set; }
		public DateTime? dis_date { get; set; }
		public string dis_union1 { get; set; }
		public string dis_class1 { get; set; }
		public string dis_union2 { get; set; }
		public string dis_class2 { get; set; }
		public DateTime? lat_date { get; set; }
		public DateTime? ref_date { get; set; }
		public string clock { get; set; }
		public string race { get; set; }
		public string sex { get; set; }
		public int eic { get; set; }
		public decimal eic_amt { get; set; }
		public string emer_phone { get; set; }
		public string emer_name { get; set; }
		public string overtime { get; set; }
		public decimal attpoints { get; set; }
		public string temptype { get; set; }
		public DateTime? sendate { get; set; }
		public string ezone { get; set; }
		public decimal dis_gross { get; set; }
		public decimal dis_fedwh { get; set; }
		public decimal dis_fica { get; set; }
		public decimal dis_med { get; set; }
		public decimal dis_net { get; set; }
		public int ta_lunch { get; set; }
		public int ta_sched { get; set; }
		public DateTime? k401_elig { get; set; }
		public DateTime? k401_enrol { get; set; }
		public int k401_per { get; set; }
		public string empgrp { get; set; }
		public string oldkey { get; set; }
	}

}
