export class hord {
  sqlid: number; // 10
  foxid: number; // 10
  custno: number; // 5
  orderno: number; // 8
  revision: string; // 1
  invno: number; // 10
  bofrom: number; // 8
  boto: number; // 8
  status: string; // 1
  ackstatus: string; // 1
  wostatus: string; // 1
  date: Date; // 8
  pono: string; // 23
  po_date?: Date; // 8
  rec_date?: Date; // 8
  rel_date?: Date; // 8
  ack_date?: Date; // 8
  ship_date?: Date; // 8
  asbl_date?: Date; // 8
  ashp_date?: Date; // 8
  invdate?: Date; // 8
  datesched?: Date; // 8
  datecancel?: Date; // 8
  holdf_date?: Date; // 8
  holdb_date?: Date; // 8
  sale1: number; // 5
  sale1per: number; // 3
  sale2: number; // 5
  sale2per: number; // 3
  sale3: number; // 5
  sale3per: number; // 3
  route: string; // 20
  pronum: string; // 12
  mark: string; // 30
  prepay: string; // 1
  lotprice: string; // 1
  blprint: string; // 1
  call: string; // 20
  call_phone: string; // 12
  hrs_before: string; // 2
  sname: string; // 25
  saddress: string; // 25
  saddress2: string; // 25
  scity: string; // 20
  sstate: string; // 2
  szip: string; // 10
  ack: string; // 50
  spec: string; // 50
  bott: string; // 50
  takenby: string; // 8
  freight: number; // 10.2
  taxable: string; // 1
  salestax: number; // 8.2
  subtotal: number; // 10.2
  arstatus: string; // 1
  commission: number; // 9.2
  credit: string; // 1
  stocking: string; // 1
  pickup: string; // 1
  ordtype: string; // 1
  paid_date?: Date; // 8
  pcom_date?: Date; // 8
  acctlock: boolean; // bool
  commlock: boolean; // bool
  cmorderno: number; // 10
  glcode: string; // 4
  commadjust: number; // 9.2
  fvendor: string; // 5
  checkmark: string; // 1
  checkdate?: Date; // 8
  checkuser: string; // 8
  subcuts: number; // 2
  currency: string; // 1
  exrate: number; // 6.4
  exrate2usd: number; // 6.4
  brokefee: number; // 7.2
  csubtotal: number; // 10.2
  csalestax: number; // 7.2
  cost: number; // 10.2
  lastrev: string; // 1
  credclear: string; // 7
  comper: number; // 3
  vcamount: number; // 9.2
  vcpaiddate?: Date; // 8
  mso: string; // 1
  tax_st: number; // 5.3
  tax_co: number; // 5.3
  tax_lo: number; // 5.3
  scounty: string; // 20
  credapp: boolean; // bool
  schday?: Date; // 8
  cc: string; // 1
  ouser: string; // 8
  cuser: string; // 8
  ordlst: string; // 1
  whse: string; // 2
  apcom: number; // 8
  apvcom: number; // 8
  terms: number; // 3
  ordstyle: string; // 3
  oldkey: number; // 8
  oldinv: number; // 10
  pallet48: number; // 2
  pallet44: number; // 2
  pallet42: number; // 2
  loosepcs: number; // 2
  crates: number; // 2
  cratewgt: number; // 4
  shq_no: string; // 10
  shq_name: string; // 15
  shq_amt: number; // 9.2
  shtrailer: number; // 6
  shname: string; // 20
  warr_yes: string; // 1
  warr_chk: string; // 8
  warr_date?: Date; // 8
  esd_newdt?: Date; // 8
  esd_lchg?: Date; // 8
  esd_lchgby: string; // 8
  esd_reason: string; // 1
  dnsb4?: Date; //8
  chgdate?: Date; // 8
  totalComm: number;
}
